//if you do not bake the surfaces generated by this library to a sprite, place this in predraw to protect against surface loss;

function ase_volitility_protection(_struct,_palette=-1){
if(!surface_exists(_struct))
{
bake_surface(_struct);	
	
}

if(struct_exists(_struct,"flat_surf"))
{
	if(!surface_exists(_struct.flat_surf))
	{
	ase_flatten_layers(_struct,_palette);	
		
	}
	
	
}


}